application: com-uchechilaka-stepwise-example
version: 1
runtime: php55
api_version: 1

handlers:
- url: /(.+\.(php|html))$
  script: \1
  
- url: /libs
  static_dir: libs
  
- url: /.*
  script: index.html